import type { NextPage } from "next";
import Head from "next/head";
import Button from "../components/Button";
// import { Table, Thead, Tbody, Tr, Th, Td } from "react-super-responsive-table";
// import "react-super-responsive-table/dist/SuperResponsiveTableStyle.css";
import Hero from "../components/Hero";
import PartDetails from "../components/PartDetails";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>SomeBikes</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero title="Bike Builder" />
			<div className="container mx-auto py-4">
				<PartDetails partType="Fork" />
				{/* <PartDetails partType="Fork" />
				<PartDetails partType="Wheelset" />
				<PartDetails partType="Brakes" />
				<PartDetails partType="Fork" /> */}
			</div>
		</div>
	);
};

export default Home;

